version: "3.6"

services:
  postgresql_database:
    image: postgres:latest
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=$PGADMIN_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_PASSWORD
    ports:
      - "${PG_ADMIN_PORT}:80"
    restart: always
    volumes:
      - pgadmin:/root/.pgadmin
volumes:
  database-data:
  pgadmin:
